package crypto

import (
	"bytes"
	"crypto/ed25519"
	"encoding/hex"
	"testing"
)

func TestVerifyEd25519_AcceptsValidSignature(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(nil)
	if err != nil {
		t.Fatalf("GenerateKey() error = %v", err)
	}
	message := []byte("the base64 enc string bytes")
	sig := ed25519.Sign(priv, message)
	if !VerifyEd25519(pub, message, sig) {
		t.Fatal("VerifyEd25519() = false, want true")
	}
}

func TestVerifyEd25519_RejectsTamperedMessage(t *testing.T) {
	pub, priv, _ := ed25519.GenerateKey(nil)
	sig := ed25519.Sign(priv, []byte("original"))
	if VerifyEd25519(pub, []byte("tampered!"), sig) {
		t.Fatal("VerifyEd25519() = true, want false for a tampered message")
	}
}

func TestVerifyEd25519_RejectsSignatureFromDifferentKey(t *testing.T) {
	pubA, _, _ := ed25519.GenerateKey(nil)
	_, privB, _ := ed25519.GenerateKey(nil)
	message := []byte("data")
	sig := ed25519.Sign(privB, message)
	if VerifyEd25519(pubA, message, sig) {
		t.Fatal("VerifyEd25519() = true, want false for a signature from a different key")
	}
}

func TestVerifyEd25519_RejectsMalformedSignatureBytes(t *testing.T) {
	pub, _, _ := ed25519.GenerateKey(nil)
	if VerifyEd25519(pub, []byte("data"), []byte("too-short")) {
		t.Fatal("VerifyEd25519() = true, want false for a malformed signature")
	}
}

func TestVerifyEd25519_RejectsInvalidPublicKeyLength(t *testing.T) {
	if VerifyEd25519([]byte("too-short-pubkey"), []byte("data"), make([]byte, ed25519.SignatureSize)) {
		t.Fatal("VerifyEd25519() = true, want false for a malformed public key")
	}
}

// TestVerifyEd25519_IndependentCrossImplementationVector verifies against
// a keypair/signature generated by OpenSSL 3.x (`openssl genpkey
// -algorithm ed25519` + `openssl pkeyutl -sign -rawin`), not Go's own
// crypto/ed25519 — an independent, cross-implementation vector proving
// this wrapper's Verify semantics agree with a second Ed25519
// implementation, the same property RFC 8032's published test vectors
// exist to establish.
func TestVerifyEd25519_IndependentCrossImplementationVector(t *testing.T) {
	pub, err := hex.DecodeString("25303ac269e9c46465950cc63b633693526237625f35cecf1c831fda36d0b569")
	if err != nil {
		t.Fatalf("decode pubkey hex: %v", err)
	}
	sig, err := hex.DecodeString("985b99b67ef16f2b2133fea29831c8f8b40055378d9dbda096c0b73d0a45d2db03dbab5fa6893042971c42b3b4054a9c9b85a941d10eba1202e9cfe8d069670d")
	if err != nil {
		t.Fatalf("decode signature hex: %v", err)
	}
	message := []byte("the base64 enc string bytes")
	if !VerifyEd25519(pub, message, sig) {
		t.Fatal("VerifyEd25519() rejected an OpenSSL-produced signature/keypair, want accept")
	}
	// Tamper the message: the same OpenSSL-produced signature must now be
	// rejected, proving the vector actually exercises verification (not a
	// vacuously-true check).
	if VerifyEd25519(pub, []byte("tampered message"), sig) {
		t.Fatal("VerifyEd25519() accepted the OpenSSL signature against a different message, want reject")
	}
}

func TestVerifyEd25519_ConsistentWithStdlibVerify(t *testing.T) {
	pub, priv, _ := ed25519.GenerateKey(nil)
	message := []byte("consistency check")
	sig := ed25519.Sign(priv, message)
	if !bytes.Equal(sig, ed25519.Sign(priv, message)) {
		t.Fatal("ed25519.Sign is not deterministic in this stdlib version — test assumption broken")
	}
	if VerifyEd25519(pub, message, sig) != ed25519.Verify(pub, message, sig) {
		t.Fatal("VerifyEd25519 disagrees with stdlib ed25519.Verify")
	}
}
