package tamga

import (
	"context"
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func representativeMachinePayloadJSON() string {
	return `{"data":{"id":"mach-id","type":"machines","attributes":{"fingerprint":"fp-abc123","cores":4,"memory":null,"disk":null,"ip":null,"hostname":"host1","platform":"linux","name":null,"heartbeat_status":"NOT_STARTED","last_heartbeat_at":null,"next_heartbeat_at":null,"last_check_out_at":null,"metadata":{},"created":"2026-01-01T00:00:00Z","updated":"2026-01-01T00:00:00Z"}}}`
}

// signForScheme signs enc (the base64 STRING, matching the section's
// shared gotcha) with a freshly generated scheme-appropriate keypair,
// returning the crypto.PublicKey value ready to pass to
// (*MachineFile).Verify, plus the raw signature bytes.
func signForScheme(t *testing.T, scheme LicenseScheme, enc string) (any, []byte) {
	t.Helper()
	switch scheme {
	case SchemeEd25519Sign:
		pub, priv, err := ed25519.GenerateKey(nil)
		if err != nil {
			t.Fatalf("ed25519.GenerateKey() error = %v", err)
		}
		return pub, ed25519.Sign(priv, []byte(enc))
	case SchemeRSA2048PKCS1Sign:
		priv, err := rsa.GenerateKey(rand.Reader, 2048)
		if err != nil {
			t.Fatalf("rsa.GenerateKey() error = %v", err)
		}
		digest := sha256.Sum256([]byte(enc))
		sig, err := rsa.SignPKCS1v15(rand.Reader, priv, crypto.SHA256, digest[:])
		if err != nil {
			t.Fatalf("rsa.SignPKCS1v15() error = %v", err)
		}
		return &priv.PublicKey, sig
	case SchemeRSA2048PKCS1PSSSign:
		priv, err := rsa.GenerateKey(rand.Reader, 2048)
		if err != nil {
			t.Fatalf("rsa.GenerateKey() error = %v", err)
		}
		digest := sha256.Sum256([]byte(enc))
		sig, err := rsa.SignPSS(rand.Reader, priv, crypto.SHA256, digest[:], nil)
		if err != nil {
			t.Fatalf("rsa.SignPSS() error = %v", err)
		}
		return &priv.PublicKey, sig
	case SchemeECDSAP256Sign:
		priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		if err != nil {
			t.Fatalf("ecdsa.GenerateKey() error = %v", err)
		}
		digest := sha256.Sum256([]byte(enc))
		sig, err := ecdsa.SignASN1(rand.Reader, priv, digest[:])
		if err != nil {
			t.Fatalf("ecdsa.SignASN1() error = %v", err)
		}
		return &priv.PublicKey, sig
	default:
		t.Fatalf("signForScheme: unsupported scheme %v", scheme)
		return nil, nil
	}
}

func schemeAlgSuffixForTest(t *testing.T, scheme LicenseScheme) string {
	t.Helper()
	suffix, err := schemeAlgSuffix(scheme)
	if err != nil {
		t.Fatalf("schemeAlgSuffix() error = %v", err)
	}
	return suffix
}

// buildSelfGeneratedMachinePEM builds a .machine PEM from this SDK's own
// understanding of the wire format.
//
// ⚠️ USE THIS ONLY FOR CASES THE SERVER CANNOT PRODUCE, and only to assert
// that Verify REJECTS something. Never to assert that a file verifies.
//
// A self-generated fixture proves nothing about format conformance: it
// reproduces whatever the verifier believes, so a verifier and a fixture that
// share a misreading agree with each other forever while no file the server
// actually emits can be opened. That is exactly how the M1/M2/M3 defects
// survived. Real conformance is asserted in machine_file_v2_test.go against
// certificates produced by the server's own encode_machine_file.
//
// payloadJSON is signed as-is so a caller can hand in a payload the server
// would never emit — e.g. one with no meta claims.
func buildSelfGeneratedMachinePEM(t *testing.T, scheme LicenseScheme, payloadJSON string) (any /* pub */, string /* pem */) {
	t.Helper()
	enc := base64.StdEncoding.EncodeToString([]byte(payloadJSON))
	pub, sig := signForScheme(t, scheme, enc)
	cert := certPayload{
		Enc: enc,
		Sig: base64.StdEncoding.EncodeToString(sig),
		Alg: "base64+" + schemeAlgSuffixForTest(t, scheme) + "+" + machineFileAlgV2Marker,
	}
	certJSON, err := json.Marshal(cert)
	if err != nil {
		t.Fatalf("json.Marshal() error = %v", err)
	}
	pemBody := base64.StdEncoding.EncodeToString(certJSON)
	return pub, machineFilePEMHeader + "\n" + pemBody + "\n" + machineFilePEMFooter
}

func TestParseMachineFile_WellFormedPEMFixture(t *testing.T) {
	pemBytes, err := os.ReadFile(serverMachineFixtureDir + "/ed25519_plain_valid.machine")
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	file, err := ParseMachineFile(string(pemBytes))
	if err != nil {
		t.Fatalf("ParseMachineFile() error = %v", err)
	}
	if file.Alg != "base64+ed25519+v2" {
		t.Errorf("Alg = %q", file.Alg)
	}
}

// TestMachineFileVerify_RejectsPreV2SelfGeneratedFixtures retires this repo's
// four original testdata/machine_file_*.machine certificates by turning them
// into what they actually are.
//
// They were generated by this SDK from its own reading of the format, and they
// carry a pre-v2 alg ("base64+ed25519", "aes-256-gcm+ecdsa-p256") with no
// signed meta claims — the shape a v1 server produced, which also derived its
// AES key by zero-padding the license key instead of through HKDF. They were
// the only thing standing behind "machine file verification works" here, and
// they passed because the verifier shared their misreading. Renamed to
// testdata/pre_v2_selfgenerated_*.machine, they are now negative fixtures for
// the rule that a file without +v2 must be refused.
//
// Each is verified against a freshly generated public key that could not
// possibly have signed it: the alg gate has to reject it anyway, and any
// ErrInvalidSignature here would mean the gate ran after the crypto instead
// of before it.
// readTestdataFixture reads a fixture from testdata/ by base name.
//
// The path is assembled here rather than at each call site so gosec's G304
// (file inclusion via variable) has a single place to look at: name comes
// from a literal table inside a test, never from input, and testdata/ is the
// only directory reachable.
func readTestdataFixture(t *testing.T, name string) ([]byte, error) {
	t.Helper()
	return os.ReadFile(filepath.Join("testdata", filepath.Base(name)))
}

func TestMachineFileVerify_RejectsPreV2SelfGeneratedFixtures(t *testing.T) {
	fixtures := map[string]LicenseScheme{
		"pre_v2_selfgenerated_ed25519.machine":   SchemeEd25519Sign,
		"pre_v2_selfgenerated_ecdsa.machine":     SchemeECDSAP256Sign,
		"pre_v2_selfgenerated_rsa_pkcs1.machine": SchemeRSA2048PKCS1Sign,
		"pre_v2_selfgenerated_rsa_pss.machine":   SchemeRSA2048PKCS1PSSSign,
	}
	for name, scheme := range fixtures {
		t.Run(name, func(t *testing.T) {
			pemBytes, err := readTestdataFixture(t, name)
			if err != nil {
				t.Fatalf("ReadFile() error = %v", err)
			}
			file, err := ParseMachineFile(string(pemBytes))
			if err != nil {
				t.Fatalf("ParseMachineFile() error = %v", err)
			}
			if strings.HasSuffix(file.Alg, "+"+machineFileAlgV2Marker) {
				t.Fatalf("fixture %s is not pre-v2 (alg = %q); it no longer tests what it claims to", name, file.Alg)
			}

			unrelatedPub, _ := signForScheme(t, scheme, "unrelated")
			_, err = file.Verify(scheme, unrelatedPub, "lic-abc123", "fp-abc123")
			if err == nil {
				t.Fatalf("Verify() accepted a pre-v2 file (alg = %q)", file.Alg)
			}
			if errors.Is(err, ErrInvalidSignature) {
				t.Errorf("pre-v2 file rejected as ErrInvalidSignature; the alg gate must run before signature verification (err = %v)", err)
			}
		})
	}
}

// TestMachineFileVerify_RejectsPayloadWithNoSignedClaims covers the one case
// the server cannot produce, so it needs a self-generated file:
// check_out_machine.rs always builds meta, so a correctly-signed v2 file whose
// payload has none is not what its own +v2 marker claims — and admitting it
// would mean an offline file with no exp to enforce.
func TestMachineFileVerify_RejectsPayloadWithNoSignedClaims(t *testing.T) {
	pub, pem := buildSelfGeneratedMachinePEM(t, SchemeEd25519Sign, representativeMachinePayloadJSON())
	file, err := ParseMachineFile(pem)
	if err != nil {
		t.Fatalf("ParseMachineFile() error = %v", err)
	}
	_, err = file.Verify(SchemeEd25519Sign, pub, "", "")
	if !errors.Is(err, ErrMissingClaims) {
		t.Fatalf("err = %v, want ErrMissingClaims", err)
	}
}

func TestCheckTTL_BoundaryValues(t *testing.T) {
	tests := []struct {
		name    string
		ttl     int
		wantErr bool
	}{
		{"zero", 0, true},
		{"one", 1, false},
		{"max", maxCheckoutTTLSeconds, false},
		{"max_plus_one", maxCheckoutTTLSeconds + 1, true},
		{"negative", -1, true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := checkTTL(tt.ttl)
			if (err != nil) != tt.wantErr {
				t.Errorf("checkTTL(%d) error = %v, wantErr %v", tt.ttl, err, tt.wantErr)
			}
			if err != nil && !errors.Is(err, ErrTTLInvalid) {
				t.Errorf("checkTTL(%d) error = %v, want it to match ErrTTLInvalid", tt.ttl, err)
			}
		})
	}
}

func TestCheckOutMachine_RejectsInvalidTTLBeforeRequest(t *testing.T) {
	var serverCalled bool
	c, closeFn := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		serverCalled = true
		w.WriteHeader(http.StatusOK)
	})
	defer closeFn()

	badTTL := 0
	_, err := c.CheckOutMachine(context.Background(), "mach-id", CheckOutOptions{TTL: &badTTL})
	if !errors.Is(err, ErrTTLInvalid) {
		t.Fatalf("err = %v, want ErrTTLInvalid", err)
	}
	if serverCalled {
		t.Fatal("server was called despite an invalid TTL — must short-circuit client-side")
	}
}

func TestCheckOutMachine_SchemeNotSupportedMapping(t *testing.T) {
	c, closeFn := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/vnd.api+json")
		w.WriteHeader(http.StatusUnprocessableEntity)
		_, _ = w.Write([]byte(`{"errors":[{"id":"e1","status":"422","code":"SCHEME_NOT_SUPPORTED","title":"Unprocessable Entity","detail":"scheme not supported"}]}`))
	})
	defer closeFn()

	_, err := c.CheckOutMachine(context.Background(), "mach-id", CheckOutOptions{UsePOST: true})
	if !errors.Is(err, ErrSchemeNotSupported) {
		t.Fatalf("errors.Is(err, ErrSchemeNotSupported) = false, err = %v", err)
	}
}

func TestCheckOutMachine_GETVariantReturnsRawPEM(t *testing.T) {
	c, closeFn := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/octet-stream")
		fixture, err := os.ReadFile(serverMachineFixtureDir + "/ed25519_plain_valid.machine")
		if err != nil {
			t.Fatalf("ReadFile() error = %v", err)
		}
		_, _ = w.Write(fixture)
	})
	defer closeFn()

	file, err := c.CheckOutMachine(context.Background(), "mach-id", CheckOutOptions{})
	if err != nil {
		t.Fatalf("CheckOutMachine() error = %v", err)
	}
	if file.Alg != "base64+ed25519+v2" {
		t.Errorf("Alg = %q", file.Alg)
	}
}

func TestCheckOutMachine_POSTVariantReturnsMachineFilesResource(t *testing.T) {
	c, closeFn := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		pemBytes, err := os.ReadFile(serverMachineFixtureDir + "/ed25519_plain_valid.machine")
		if err != nil {
			t.Fatalf("ReadFile() error = %v", err)
		}
		w.Header().Set("Content-Type", "application/vnd.api+json")
		resp := fmt.Sprintf(`{"data":{"id":"cert-id","type":"machine-files","attributes":{"certificate":%q,"algorithm":"base64+ed25519+v2","includes":[],"ttl":null,"expiry":null,"issued":"2026-01-01T00:00:00Z"}}}`, string(pemBytes))
		_, _ = w.Write([]byte(resp))
	})
	defer closeFn()

	file, err := c.CheckOutMachine(context.Background(), "mach-id", CheckOutOptions{UsePOST: true})
	if err != nil {
		t.Fatalf("CheckOutMachine() error = %v", err)
	}
	if file.ID != "cert-id" {
		t.Errorf("ID = %q", file.ID)
	}
}
