package tamga

// signing_key_test.go proves the kid derivation and the key set against
// vectors this SDK did not produce.
//
// testdata/signing-key-ids.json was generated by an independent SHA-256
// implementation and cross-checked against tamga-rust's committed vector,
// deliberately NOT by any SDK — a fixture an SDK generated can only prove
// that SDK agrees with itself, which is precisely how this repo's machine
// file defects stayed green for two years (see machine_file_v2_test.go).
//
// The negative vector is the one that matters most. The same key hashes to
// 905f28def18eaac0 correctly and to 630dcd2966c43366 if the base64 is
// decoded before hashing, and decoding first is the natural assumption. A
// suite that asserts only the positive value cannot tell a correct
// implementation from one that got lucky, so both are asserted here.

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// signingKeyVectors is testdata/signing-key-ids.json.
type signingKeyVectors struct {
	// Negative leads the struct only to satisfy govet's fieldalignment
	// check; field order here carries no meaning.
	Negative struct {
		Name              string `json:"name"`
		PublicKey         string `json:"publicKey"`
		CorrectKID        string `json:"correctKid"`
		WrongKIDIfDecoded string `json:"wrongKidIfDecodedFirst"`
		Note              string `json:"note"`
	} `json:"negative"`
	Vectors []struct {
		Name      string `json:"name"`
		PublicKey string `json:"publicKey"`
		KID       string `json:"kid"`
		Note      string `json:"note"`
	} `json:"vectors"`
}

func loadSigningKeyVectors(t *testing.T) signingKeyVectors {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "signing-key-ids.json"))
	if err != nil {
		t.Fatalf("ReadFile(signing-key-ids.json) error = %v", err)
	}
	var v signingKeyVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("json.Unmarshal(signing-key-ids.json) error = %v", err)
	}
	if len(v.Vectors) == 0 {
		t.Fatal("signing-key-ids.json declares no vectors")
	}
	return v
}

func TestKeyID_MatchesIndependentVectors(t *testing.T) {
	vectors := loadSigningKeyVectors(t)
	for _, vec := range vectors.Vectors {
		t.Run(vec.Name, func(t *testing.T) {
			if got := KeyID(vec.PublicKey); got != vec.KID {
				t.Errorf("KeyID(%q) = %q, want %q\nvector note: %s", vec.PublicKey, got, vec.KID, vec.Note)
			}
		})
	}
}

// TestKeyID_HashesTheBase64StringNotTheDecodedBytes is the regression test
// that actually pins the contract, and it is more important than the
// happy-path vectors above.
//
// The server hands key_id the stored base64 &str
// (tamga-api/src/shared/crypto/license_file.rs:70), never the 32 bytes it
// decodes to. Decoding first is the natural assumption and it is wrong: it
// yields a different id for the same key, matching nothing the server has
// ever emitted, and every rotation-aware verification silently reports
// authentic files as signed by an unknown key.
//
// Asserting the correct value alone does not catch that — an implementation
// has to be shown NOT to produce the wrong one.
func TestKeyID_HashesTheBase64StringNotTheDecodedBytes(t *testing.T) {
	neg := loadSigningKeyVectors(t).Negative
	got := KeyID(neg.PublicKey)
	if got != neg.CorrectKID {
		t.Errorf("KeyID(%q) = %q, want %q", neg.PublicKey, got, neg.CorrectKID)
	}
	if got == neg.WrongKIDIfDecoded {
		t.Fatalf("KeyID decoded the base64 before hashing: got %q, the value that proves it. "+
			"The digest must be taken over the base64 STRING's own bytes. Vector note: %s",
			got, neg.Note)
	}
}

// TestKeyID_MatchesTheKidsInServerIssuedFixtures cross-checks the hash rule
// against certificates the tamga-api server actually produced, independently
// of testdata/signing-key-ids.json.
//
// ⚠️ It pins the HASH RULE only, not which key a real checkout names. The
// fixture generator derived each file's kid from that file's own signing
// key, including for the RSA and ECDSA fixtures; a real server derives it
// from account.ed25519_public_key whatever scheme signed the bytes
// (check_out_machine.rs:127). So a non-Ed25519 fixture's kid is not what a
// production file would carry — it is still a genuine, server-computed
// SHA-256-over-the-base64-string, which is the only thing asserted here.
func TestKeyID_MatchesTheKidsInServerIssuedFixtures(t *testing.T) {
	for _, fx := range loadServerMachineFixtures(t) {
		t.Run(fx.Name, func(t *testing.T) {
			if got := KeyID(fx.PublicKeyB64); got != fx.KID {
				t.Errorf("KeyID(public_key_b64) = %q, manifest kid = %q", got, fx.KID)
			}
		})
	}
}

// TestKeyID_UnpublishedAccountSentinel pins the constant an account with no
// Ed25519 public key signs everything with. Both checkout handlers call
// key_id(account.ed25519_public_key.unwrap_or_default()), so an unbackfilled
// account produces KeyID("") on every file it issues, and recognising it is
// what separates "refresh your key set" from "there is no key to fetch".
func TestKeyID_UnpublishedAccountSentinel(t *testing.T) {
	if got := KeyID(""); got != UnpublishedSigningKeyID {
		t.Errorf("KeyID(\"\") = %q, want UnpublishedSigningKeyID %q", got, UnpublishedSigningKeyID)
	}
	// Cross-checked against the independent vector set, not just against
	// the constant this package declares.
	for _, vec := range loadSigningKeyVectors(t).Vectors {
		if vec.PublicKey == "" && vec.KID != UnpublishedSigningKeyID {
			t.Errorf("UnpublishedSigningKeyID = %q, independent vector %q says %q", UnpublishedSigningKeyID, vec.Name, vec.KID)
		}
	}
}

func TestKeyID_IsAlwaysSixteenLowercaseHexChars(t *testing.T) {
	const hexDigits = "0123456789abcdef"
	for _, in := range []string{"", "A", strings.Repeat("z", 1000), "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="} {
		got := KeyID(in)
		if len(got) != 16 {
			t.Errorf("KeyID(%.10q) = %q, want 16 characters", in, got)
		}
		if strings.ContainsFunc(got, func(r rune) bool { return !strings.ContainsRune(hexDigits, r) }) {
			t.Errorf("KeyID(%.10q) = %q, want lowercase hex only", in, got)
		}
	}
}

// --- key set -------------------------------------------------------------

// zeroKeyB64 is base64 of 32 zero bytes: a well-formed Ed25519 key encoding,
// used here only for its length and its kid (the primary vector).
const zeroKeyB64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

const zeroKeyKID = "51643eac9777b63a"

func signingKeyResource(id, algorithm, publicKey string, retired *string) SigningKey {
	return SigningKey{
		ID:   id,
		Type: "signing-keys",
		Attributes: SigningKeyAttributes{
			Algorithm: algorithm,
			PublicKey: publicKey,
			Status:    "active",
			Created:   "2026-01-01T00:00:00Z",
			Retired:   retired,
		},
	}
}

func TestNewSigningKeySet_IndexesByTheServedResourceID(t *testing.T) {
	// The server's id IS the kid (accounts/serializer.rs:102), so the set
	// must index by it and must not silently re-key entries by whatever it
	// computes locally.
	set := NewSigningKeySet([]SigningKey{signingKeyResource("deadbeefdeadbeef", "ed25519", zeroKeyB64, nil)})
	if _, ok := set.Find("deadbeefdeadbeef"); !ok {
		t.Error("Find(served id) = false, want the set to index by the resource id")
	}
	if got := set.KeyIDs(); len(got) != 1 || got[0] != "deadbeefdeadbeef" {
		t.Errorf("KeyIDs() = %v, want the served id", got)
	}
}

func TestNewSigningKeySet_SkipsUnusableRowsWithoutStrandingTheRest(t *testing.T) {
	// A future algorithm and a key that does not decode are skipped; the
	// Ed25519 rows around them still verify their files. Failing the whole
	// response would strand every file the account ever signed.
	set := NewSigningKeySet([]SigningKey{
		signingKeyResource("0000000000000000", "ml-dsa-44", zeroKeyB64, nil),
		signingKeyResource("1111111111111111", "ed25519", "!!!not base64!!!", nil),
		signingKeyResource("2222222222222222", "ed25519", "QUJD", nil), // 3 bytes, not 32
		signingKeyResource("3333333333333333", "ed25519", zeroKeyB64, nil),
	})
	if set.Len() != 1 {
		t.Fatalf("Len() = %d, want 1 usable key out of 4 rows", set.Len())
	}
	for _, kid := range []string{"0000000000000000", "1111111111111111", "2222222222222222"} {
		if _, ok := set.Find(kid); ok {
			t.Errorf("Find(%q) = true, want the unusable row skipped", kid)
		}
	}
	if _, ok := set.Find("3333333333333333"); !ok {
		t.Error("Find(usable row) = false, one bad row stranded the good one")
	}
}

func TestNewSigningKeySet_RetiredKeysAreKept(t *testing.T) {
	// The retired keys are the entire point of the route: a file signed
	// before the last rotation needs the key that signed it.
	retiredAt := "2026-06-01T00:00:00Z"
	set := NewSigningKeySet([]SigningKey{
		signingKeyResource("aaaaaaaaaaaaaaaa", "ed25519", zeroKeyB64, &retiredAt),
		signingKeyResource("bbbbbbbbbbbbbbbb", "ed25519", zeroKeyB64, nil),
	})
	if set.Len() != 2 {
		t.Fatalf("Len() = %d, want 2 — a retired key must not be filtered out", set.Len())
	}
	retired, ok := set.Find("aaaaaaaaaaaaaaaa")
	if !ok {
		t.Fatal("Find(retired key) = false, want the retired key kept")
	}
	if !retired.IsRetired() {
		t.Error("IsRetired() = false for a key carrying a retired timestamp")
	}
	active, _ := set.Find("bbbbbbbbbbbbbbbb")
	if active.IsRetired() {
		t.Error("IsRetired() = true for a key with no retired timestamp — absent means active")
	}
}

func TestSigningKeySet_MismatchedDetectsAServedIDThatDisagreesWithTheKey(t *testing.T) {
	// The local computation is a cross-check on a value the API hands over
	// ready-made, not a second source of truth: a mismatched row is still
	// usable, under either id, and is merely reported.
	set := NewSigningKeySet([]SigningKey{
		signingKeyResource("mismatched000000", "ed25519", zeroKeyB64, nil),
		signingKeyResource(zeroKeyKID, "ed25519", zeroKeyB64, nil),
	})
	got := set.Mismatched()
	if len(got) != 1 || got[0] != "mismatched000000" {
		t.Errorf("Mismatched() = %v, want exactly the row whose id disagrees with KeyID(publicKey)", got)
	}
	if _, ok := set.Find("mismatched000000"); !ok {
		t.Error("Find(served id) = false for a mismatched row; it must still resolve")
	}
	if _, ok := set.Find(zeroKeyKID); !ok {
		t.Error("Find(computed id) = false for a mismatched row; it must resolve under either id")
	}
}

func TestSigningKeySet_MismatchedIsEmptyForAHealthySet(t *testing.T) {
	set := NewSigningKeySet([]SigningKey{signingKeyResource(zeroKeyKID, "ed25519", zeroKeyB64, nil)})
	if got := set.Mismatched(); len(got) != 0 {
		t.Errorf("Mismatched() = %v, want empty when every served id hashes to itself", got)
	}
}

func TestNewSigningKeySetFromPublicKeys_IndexesByComputedKeyID(t *testing.T) {
	set, err := NewSigningKeySetFromPublicKeys(zeroKeyB64)
	if err != nil {
		t.Fatalf("NewSigningKeySetFromPublicKeys() error = %v", err)
	}
	if set.Len() != 1 {
		t.Fatalf("Len() = %d, want 1", set.Len())
	}
	if _, ok := set.Find(zeroKeyKID); !ok {
		t.Errorf("Find(%q) = false, want the pinned key indexed by its computed kid", zeroKeyKID)
	}
	if got := set.Mismatched(); len(got) != 0 {
		t.Errorf("Mismatched() = %v, want empty on the offline path", got)
	}
}

func TestNewSigningKeySetFromPublicKeys_RejectsAMistypedKeyLoudly(t *testing.T) {
	// The alternative — skipping it, as the fetched path does — produces a
	// set that reports every genuine file as signed by an unknown key, at
	// runtime, in the field. A key pinned in a binary must fail at startup.
	for _, tc := range []struct{ name, key string }{
		{"not base64", "not base64 at all"},
		{"too short", "QUJD"},
		{"too long", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := NewSigningKeySetFromPublicKeys(tc.key); err == nil {
				t.Errorf("NewSigningKeySetFromPublicKeys(%q) error = nil, want a loud failure", tc.key)
			}
		})
	}
}

func TestSigningKeySet_FindIsExact(t *testing.T) {
	set, err := NewSigningKeySetFromPublicKeys(zeroKeyB64)
	if err != nil {
		t.Fatalf("NewSigningKeySetFromPublicKeys() error = %v", err)
	}
	for _, kid := range []string{strings.ToUpper(zeroKeyKID), zeroKeyKID[:15], "", zeroKeyKID + "0"} {
		if _, ok := set.Find(kid); ok {
			t.Errorf("Find(%q) = true, want exact case-sensitive matching only", kid)
		}
	}
}

func TestSigningKeySet_NilAndEmptyAreSafe(t *testing.T) {
	var nilSet *SigningKeySet
	empty := NewSigningKeySet(nil)
	for name, set := range map[string]*SigningKeySet{"nil": nilSet, "empty": empty} {
		t.Run(name, func(t *testing.T) {
			if set.Len() != 0 {
				t.Errorf("Len() = %d, want 0", set.Len())
			}
			if got := set.KeyIDs(); len(got) != 0 {
				t.Errorf("KeyIDs() = %v, want empty", got)
			}
			if got := set.Keys(); len(got) != 0 {
				t.Errorf("Keys() = %v, want empty", got)
			}
			if got := set.Mismatched(); len(got) != 0 {
				t.Errorf("Mismatched() = %v, want empty", got)
			}
			if _, ok := set.Find(zeroKeyKID); ok {
				t.Error("Find() = true on an empty set")
			}
		})
	}
}

// --- wire shape ----------------------------------------------------------

// TestSigningKey_DecodesTheServerSerializerShape pins the response shape
// against accounts/serializer.rs, whose per-field rename on public_key is
// the ONLY camelCase field in an otherwise bare attribute bag.
func TestSigningKey_DecodesTheServerSerializerShape(t *testing.T) {
	const body = `{
		"type":"signing-keys",
		"id":"51643eac9777b63a",
		"attributes":{
			"algorithm":"ed25519",
			"publicKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
			"status":"retired",
			"created":"2026-01-01T00:00:00Z",
			"retired":"2026-06-01T00:00:00Z"
		}
	}`
	var key SigningKey
	if err := json.Unmarshal([]byte(body), &key); err != nil {
		t.Fatalf("json.Unmarshal error = %v", err)
	}
	if key.ID != "51643eac9777b63a" {
		t.Errorf("ID = %q, want the kid — this resource is not identified by a UUID", key.ID)
	}
	if key.Type != "signing-keys" {
		t.Errorf("Type = %q", key.Type)
	}
	if key.Attributes.PublicKey != zeroKeyB64 {
		t.Errorf("PublicKey = %q — the wire name is camelCase publicKey", key.Attributes.PublicKey)
	}
	if key.Attributes.Status != "retired" || key.Attributes.Algorithm != "ed25519" {
		t.Errorf("Attributes = %+v", key.Attributes)
	}
	if key.Attributes.Retired == nil || *key.Attributes.Retired != "2026-06-01T00:00:00Z" {
		t.Errorf("Retired = %v, want the timestamp", key.Attributes.Retired)
	}
	if !key.IsRetired() {
		t.Error("IsRetired() = false")
	}
}

// TestSigningKey_ActiveKeyOmitsRetiredEntirely pins the server's
// skip_serializing_if: an active key has no retired field at all, rather
// than a null one.
func TestSigningKey_ActiveKeyOmitsRetiredEntirely(t *testing.T) {
	const body = `{"type":"signing-keys","id":"51643eac9777b63a","attributes":{
		"algorithm":"ed25519","publicKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
		"status":"active","created":"2026-01-01T00:00:00Z"}}`
	var key SigningKey
	if err := json.Unmarshal([]byte(body), &key); err != nil {
		t.Fatalf("json.Unmarshal error = %v", err)
	}
	if key.Attributes.Retired != nil {
		t.Errorf("Retired = %v, want nil when the field is absent", key.Attributes.Retired)
	}
	if key.IsRetired() {
		t.Error("IsRetired() = true for an active key")
	}
}

// TestSigningKey_SnakeCasePublicKeyDoesNotDecode is the negative half of the
// camelCase rule: a fixture written from these struct tags' snake_case
// sibling must NOT populate the field, or a wrong-cased server response
// would silently produce an empty key rather than an obvious failure.
func TestSigningKey_SnakeCasePublicKeyDoesNotDecode(t *testing.T) {
	const body = `{"type":"signing-keys","id":"51643eac9777b63a","attributes":{
		"algorithm":"ed25519","public_key":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
		"status":"active","created":"2026-01-01T00:00:00Z"}}`
	var key SigningKey
	if err := json.Unmarshal([]byte(body), &key); err != nil {
		t.Fatalf("json.Unmarshal error = %v", err)
	}
	if key.Attributes.PublicKey != "" {
		t.Errorf("PublicKey = %q from a snake_case body; the wire name is publicKey only", key.Attributes.PublicKey)
	}
	// And such a row must then be skipped by the set rather than kept as a
	// key that can never verify anything.
	if got := NewSigningKeySet([]SigningKey{key}).Len(); got != 0 {
		t.Errorf("Len() = %d, want the undecodable row skipped", got)
	}
}

func TestSigningKey_UnknownAlgorithmOrStatusStillDecodes(t *testing.T) {
	const body = `{"type":"signing-keys","id":"0011223344556677","attributes":{
		"algorithm":"ml-dsa-44","publicKey":"AAAA","status":"compromised",
		"created":"2026-01-01T00:00:00Z"}}`
	var key SigningKey
	if err := json.Unmarshal([]byte(body), &key); err != nil {
		t.Fatalf("json.Unmarshal error = %v", err)
	}
	if key.Attributes.Algorithm != "ml-dsa-44" || key.Attributes.Status != "compromised" {
		t.Errorf("Attributes = %+v, want open strings rather than enums", key.Attributes)
	}
}

// --- client --------------------------------------------------------------

func TestListSigningKeys_RequestsTheAccountScopedRoute(t *testing.T) {
	var gotPath, gotMethod string
	c, closeFn := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		gotPath, gotMethod = r.URL.Path, r.Method
		w.Header().Set("Content-Type", "application/vnd.api+json")
		_, _ = w.Write([]byte(`{"data":[
			{"type":"signing-keys","id":"51643eac9777b63a","attributes":{"algorithm":"ed25519","publicKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","status":"retired","created":"2026-01-01T00:00:00Z","retired":"2026-06-01T00:00:00Z"}},
			{"type":"signing-keys","id":"905f28def18eaac0","attributes":{"algorithm":"ed25519","publicKey":"AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=","status":"active","created":"2026-06-01T00:00:00Z"}}
		]}`))
	})
	defer closeFn()

	keys, err := c.ListSigningKeys(context.Background())
	if err != nil {
		t.Fatalf("ListSigningKeys() error = %v", err)
	}
	if gotMethod != "GET" {
		t.Errorf("method = %s, want GET", gotMethod)
	}
	if !strings.HasSuffix(gotPath, "/v1/accounts/acct-123/signing-keys") {
		t.Errorf("path = %s, want the account-scoped /signing-keys route", gotPath)
	}
	if len(keys) != 2 {
		t.Fatalf("len(keys) = %d, want 2 — the retired key must come back too", len(keys))
	}
	if !keys[0].IsRetired() || keys[1].IsRetired() {
		t.Errorf("retired flags = %v/%v, want the first retired and the second active", keys[0].IsRetired(), keys[1].IsRetired())
	}
}

func TestGetSigningKeySet_BuildsAUsableSetIncludingRetiredKeys(t *testing.T) {
	c, closeFn := newTestClient(t, func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/vnd.api+json")
		_, _ = w.Write([]byte(`{"data":[
			{"type":"signing-keys","id":"51643eac9777b63a","attributes":{"algorithm":"ed25519","publicKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","status":"retired","created":"2026-01-01T00:00:00Z","retired":"2026-06-01T00:00:00Z"}},
			{"type":"signing-keys","id":"905f28def18eaac0","attributes":{"algorithm":"ed25519","publicKey":"AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=","status":"active","created":"2026-06-01T00:00:00Z"}}
		]}`))
	})
	defer closeFn()

	set, err := c.GetSigningKeySet(context.Background())
	if err != nil {
		t.Fatalf("GetSigningKeySet() error = %v", err)
	}
	if set.Len() != 2 {
		t.Fatalf("Len() = %d, want 2", set.Len())
	}
	// Both ids are the independent vectors' kids, so a healthy fetch must
	// report no mismatch at all.
	if got := set.Mismatched(); len(got) != 0 {
		t.Errorf("Mismatched() = %v, want empty for a consistent published set", got)
	}
	if _, ok := set.Find("51643eac9777b63a"); !ok {
		t.Error("the retired key is missing from the set")
	}
}

func TestListSigningKeys_ForbiddenUnderLicenseKeyAuthSurfacesAsIs(t *testing.T) {
	// account.read is not in the LicenseToken role's permission set
	// (authz/mod.rs), so an embedded client gets 403 here unconditionally.
	// The SDK must pass that through rather than dress it up: the fix is
	// NewSigningKeySetFromPublicKeys, not a retry.
	c, closeFn := newTestClient(t, func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/vnd.api+json")
		w.WriteHeader(http.StatusForbidden)
		_, _ = w.Write([]byte(`{"errors":[{"status":"403","code":"FORBIDDEN","title":"Forbidden","detail":"insufficient permissions"}]}`))
	})
	defer closeFn()

	if _, err := c.ListSigningKeys(context.Background()); !errors.Is(err, ErrForbidden) {
		t.Errorf("ListSigningKeys() error = %v, want ErrForbidden", err)
	}
}
